[project]
name = "toutiao-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiomysql>=0.3.2",
    "bcrypt<4.1.0",
    "fastapi[standard]>=0.129.2",
    "passlib[bcrypt]>=1.7.4",
    "sqlalchemy[asyncio]>=2.0.46",
]
